### PR TITLE
Added Arda Maps database

### PR DESCRIPTION
**Pull request by kwoxer**

### CODE REVIEW

**Comment by lvca** [comment]
Did you change the default password from "admin" ?

**Comment by kwoxer** [comment]
Yes, is this an issue? =/

I created a user _arda_ with password _arda_ that has minimal rights.

**Comment by lvca** [comment]
Ok, restored admin ;-) It's online now. I've hosted it under our servers.

**Comment by lvca** [comment]
Merged manually.

**Comment by lvca** [comment]
By the way I changed default representation of vertices in studio to display the names instead o RID.

**Comment by kwoxer** [comment]
Ok great. =)

So I can delete the zip from my server right?

**Comment by lvca** [comment]
yes

**Pull request closed without merging**
